package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "author", catalog = "testHibernate")
public class Author implements java.io.Serializable {

    private Integer idAuthor;
    private String fname;
    private String lname;
    private String pname;
    private Set<Book> books = new HashSet<Book>(0);

    public Author() {
    }

    public Author(String fname, String lname) {
        this.fname = fname;
        this.lname = lname;
    }

    public Author(String fname, String lname, String pname, Set<Book> books) {
        this.fname = fname;
        this.lname = lname;
        this.pname = pname;
        this.books = books;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_author", unique = true, nullable = false)
    public Integer getIdAuthor() {
        return this.idAuthor;
    }

    public void setIdAuthor(Integer idAuthor) {
        this.idAuthor = idAuthor;
    }

    @Column(name = "fname", nullable = false, length = 50)
    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    @Column(name = "lname", nullable = false, length = 50)
    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    @Column(name = "pname", length = 50)
    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "bookAuthor", catalog = "testHibernate", joinColumns = {
        @JoinColumn(name = "id_author", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "ib_book", nullable = false, updatable = false)})
    public Set<Book> getBooks() {
        return this.books;
    }

    public void setBooks(Set<Book> books) {
        this.books = books;
    }

    @Transient
    public String getFullName() {
        if (pname == null) {
            return lname + fname;
        }
        return lname + fname + pname;
    }

    @Override
    public String toString() {
        return "Author{" + "idAuthor=" + idAuthor + ", fname=" + fname + ", lname=" + lname + ", pname=" + pname + '}';
    }
}
