package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BookWarehouse generated by hbm2java
 */
@Entity
@Table(name="bookWarehouse"
    ,catalog="testHibernate"
)
public class BookWarehouse  implements java.io.Serializable {


     private BookWarehouseId id;
     private Warehouse warehouse;
     private Book book;
     private int cntWarehouse;

    public BookWarehouse() {
    }

    public BookWarehouse(BookWarehouseId id, Warehouse warehouse, Book book, int cntWarehouse) {
       this.id = id;
       this.warehouse = warehouse;
       this.book = book;
       this.cntWarehouse = cntWarehouse;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idBook", column=@Column(name="id_book", nullable=false) ), 
        @AttributeOverride(name="idWarehouse", column=@Column(name="id_warehouse", nullable=false) ) } )
    public BookWarehouseId getId() {
        return this.id;
    }
    
    public void setId(BookWarehouseId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_warehouse", nullable=false, insertable=false, updatable=false)
    public Warehouse getWarehouse() {
        return this.warehouse;
    }
    
    public void setWarehouse(Warehouse warehouse) {
        this.warehouse = warehouse;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_book", nullable=false, insertable=false, updatable=false)
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }

    
    @Column(name="cnt_warehouse", nullable=false)
    public int getCntWarehouse() {
        return this.cntWarehouse;
    }
    
    public void setCntWarehouse(int cntWarehouse) {
        this.cntWarehouse = cntWarehouse;
    }




}


