package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BookWarehouseId generated by hbm2java
 */
@Embeddable
public class BookWarehouseId  implements java.io.Serializable {


     private int idBook;
     private int idWarehouse;

    public BookWarehouseId() {
    }

    public BookWarehouseId(int idBook, int idWarehouse) {
       this.idBook = idBook;
       this.idWarehouse = idWarehouse;
    }
   


    @Column(name="id_book", nullable=false)
    public int getIdBook() {
        return this.idBook;
    }
    
    public void setIdBook(int idBook) {
        this.idBook = idBook;
    }


    @Column(name="id_warehouse", nullable=false)
    public int getIdWarehouse() {
        return this.idWarehouse;
    }
    
    public void setIdWarehouse(int idWarehouse) {
        this.idWarehouse = idWarehouse;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BookWarehouseId) ) return false;
		 BookWarehouseId castOther = ( BookWarehouseId ) other; 
         
		 return (this.getIdBook()==castOther.getIdBook())
 && (this.getIdWarehouse()==castOther.getIdWarehouse());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdBook();
         result = 37 * result + this.getIdWarehouse();
         return result;
   }   


}


