package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Discount generated by hbm2java
 */
@Entity
@Table(name="discount"
    ,catalog="testHibernate"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Discount  implements java.io.Serializable {


     private Integer idDiscount;
     private Date dts;
     private Date dte;
     private char flGroup;
     private int rate;
     private String name;
     private String description;
     private Set<GroupBookDiscount> groupBookDiscounts = new HashSet<GroupBookDiscount>(0);
     private Set<Book> books = new HashSet<Book>(0);

    public Discount() {
    }

	
    public Discount(Date dts, Date dte, char flGroup, int rate, String name, String description) {
        this.dts = dts;
        this.dte = dte;
        this.flGroup = flGroup;
        this.rate = rate;
        this.name = name;
        this.description = description;
    }
    public Discount(Date dts, Date dte, char flGroup, int rate, String name, String description, Set<GroupBookDiscount> groupBookDiscounts, Set<Book> books) {
       this.dts = dts;
       this.dte = dte;
       this.flGroup = flGroup;
       this.rate = rate;
       this.name = name;
       this.description = description;
       this.groupBookDiscounts = groupBookDiscounts;
       this.books = books;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_discount", unique=true, nullable=false)
    public Integer getIdDiscount() {
        return this.idDiscount;
    }
    
    public void setIdDiscount(Integer idDiscount) {
        this.idDiscount = idDiscount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dts", nullable=false, length=10)
    public Date getDts() {
        return this.dts;
    }
    
    public void setDts(Date dts) {
        this.dts = dts;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dte", nullable=false, length=10)
    public Date getDte() {
        return this.dte;
    }
    
    public void setDte(Date dte) {
        this.dte = dte;
    }

    
    @Column(name="fl_group", nullable=false, length=1)
    public char getFlGroup() {
        return this.flGroup;
    }
    
    public void setFlGroup(char flGroup) {
        this.flGroup = flGroup;
    }

    
    @Column(name="rate", nullable=false)
    public int getRate() {
        return this.rate;
    }
    
    public void setRate(int rate) {
        this.rate = rate;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="discount")
    public Set<GroupBookDiscount> getGroupBookDiscounts() {
        return this.groupBookDiscounts;
    }
    
    public void setGroupBookDiscounts(Set<GroupBookDiscount> groupBookDiscounts) {
        this.groupBookDiscounts = groupBookDiscounts;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="discountBookSingle", catalog="testHibernate", joinColumns = { 
        @JoinColumn(name="id_discount", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_book", nullable=false, updatable=false) })
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }




}


