package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupBookDiscount generated by hbm2java
 */
@Entity
@Table(name="groupBookDiscount"
    ,catalog="testHibernate"
)
public class GroupBookDiscount  implements java.io.Serializable {


     private Integer idGroupBook;
     private Discount discount;
     private Set<Book> books = new HashSet<Book>(0);

    public GroupBookDiscount() {
    }

	
    public GroupBookDiscount(Discount discount) {
        this.discount = discount;
    }
    public GroupBookDiscount(Discount discount, Set<Book> books) {
       this.discount = discount;
       this.books = books;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_groupBook", unique=true, nullable=false)
    public Integer getIdGroupBook() {
        return this.idGroupBook;
    }
    
    public void setIdGroupBook(Integer idGroupBook) {
        this.idGroupBook = idGroupBook;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_discount", nullable=false)
    public Discount getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Discount discount) {
        this.discount = discount;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="groupBook", catalog="testHibernate", joinColumns = { 
        @JoinColumn(name="id_groupBook", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_book", nullable=false, updatable=false) })
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }




}


