package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderUser generated by hbm2java
 */
@Entity
@Table(name="orderUser"
    ,catalog="testHibernate"
)
public class OrderUser  implements java.io.Serializable {


     private Integer idOrder;
     private User user;
     private Date date;
     private int sum;
     private Set<OrderBook> orderBooks = new HashSet<OrderBook>(0);

    public OrderUser() {
    }

	
    public OrderUser(User user, Date date, int sum) {
        this.user = user;
        this.date = date;
        this.sum = sum;
    }
    public OrderUser(User user, Date date, int sum, Set<OrderBook> orderBooks) {
       this.user = user;
       this.date = date;
       this.sum = sum;
       this.orderBooks = orderBooks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_order", unique=true, nullable=false)
    public Integer getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="sum", nullable=false)
    public int getSum() {
        return this.sum;
    }
    
    public void setSum(int sum) {
        this.sum = sum;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orderUser")
    public Set<OrderBook> getOrderBooks() {
        return this.orderBooks;
    }
    
    public void setOrderBooks(Set<OrderBook> orderBooks) {
        this.orderBooks = orderBooks;
    }




}


