package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderBookId generated by hbm2java
 */
@Embeddable
public class OrderBookId  implements java.io.Serializable {


     private int idOrder;
     private int idBook;

    public OrderBookId() {
    }

    public OrderBookId(int idOrder, int idBook) {
       this.idOrder = idOrder;
       this.idBook = idBook;
    }
   


    @Column(name="id_order", nullable=false)
    public int getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(int idOrder) {
        this.idOrder = idOrder;
    }


    @Column(name="id_book", nullable=false)
    public int getIdBook() {
        return this.idBook;
    }
    
    public void setIdBook(int idBook) {
        this.idBook = idBook;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderBookId) ) return false;
		 OrderBookId castOther = ( OrderBookId ) other; 
         
		 return (this.getIdOrder()==castOther.getIdOrder())
 && (this.getIdBook()==castOther.getIdBook());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOrder();
         result = 37 * result + this.getIdBook();
         return result;
   }   


}


