package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderBook generated by hbm2java
 */
@Entity
@Table(name="orderBook"
    ,catalog="testHibernate"
)
public class OrderBook  implements java.io.Serializable {


     private OrderBookId id;
     private OrderUser orderUser;
     private Book book;
     private int cnt;

    public OrderBook() {
    }

    public OrderBook(OrderBookId id, OrderUser orderUser, Book book, int cnt) {
       this.id = id;
       this.orderUser = orderUser;
       this.book = book;
       this.cnt = cnt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idOrder", column=@Column(name="id_order", nullable=false) ), 
        @AttributeOverride(name="idBook", column=@Column(name="id_book", nullable=false) ) } )
    public OrderBookId getId() {
        return this.id;
    }
    
    public void setId(OrderBookId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_order", nullable=false, insertable=false, updatable=false)
    public OrderUser getOrderUser() {
        return this.orderUser;
    }
    
    public void setOrderUser(OrderUser orderUser) {
        this.orderUser = orderUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_book", nullable=false, insertable=false, updatable=false)
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }

    
    @Column(name="cnt", nullable=false)
    public int getCnt() {
        return this.cnt;
    }
    
    public void setCnt(int cnt) {
        this.cnt = cnt;
    }




}


