package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="testHibernate"
    , uniqueConstraints = {@UniqueConstraint(columnNames="log"), @UniqueConstraint(columnNames="email")} 
)
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String log;
     private String email;
     private String pas;
     private char isActive;
     private UserInfo userInfo;
     private Set<OrderUser> orderUsers = new HashSet<OrderUser>(0);

    public User() {
    }

	
    public User(String log, String email, String pas, char isActive) {
        this.log = log;
        this.email = email;
        this.pas = pas;
        this.isActive = isActive;
    }
    public User(String log, String email, String pas, char isActive, UserInfo userInfo, Set<OrderUser> orderUsers) {
       this.log = log;
       this.email = email;
       this.pas = pas;
       this.isActive = isActive;
       this.userInfo = userInfo;
       this.orderUsers = orderUsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_user", unique=true, nullable=false)
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="log", unique=true, nullable=false, length=20)
    public String getLog() {
        return this.log;
    }
    
    public void setLog(String log) {
        this.log = log;
    }

    
    @Column(name="email", unique=true, nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="pas", nullable=false, length=20)
    public String getPas() {
        return this.pas;
    }
    
    public void setPas(String pas) {
        this.pas = pas;
    }

    
    @Column(name="isActive", nullable=false, length=1)
    public char getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(char isActive) {
        this.isActive = isActive;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<OrderUser> getOrderUsers() {
        return this.orderUsers;
    }
    
    public void setOrderUsers(Set<OrderUser> orderUsers) {
        this.orderUsers = orderUsers;
    }




}


