package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name="userInfo"
    ,catalog="testHibernate"
)
public class UserInfo  implements java.io.Serializable {


     private int idUser;
     private User user;
     private String fname;
     private String lname;
     private String pname;
     private String phone;
     private Date birsday;
     private char sex;

    public UserInfo() {
    }

    public UserInfo(User user, String fname, String lname, String pname, String phone, Date birsday, char sex) {
       this.user = user;
       this.fname = fname;
       this.lname = lname;
       this.pname = pname;
       this.phone = phone;
       this.birsday = birsday;
       this.sex = sex;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="user"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_user", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="fname", nullable=false, length=50)
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }

    
    @Column(name="lname", nullable=false, length=50)
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }

    
    @Column(name="pname", nullable=false, length=50)
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }

    
    @Column(name="phone", nullable=false, length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birsday", nullable=false, length=10)
    public Date getBirsday() {
        return this.birsday;
    }
    
    public void setBirsday(Date birsday) {
        this.birsday = birsday;
    }

    
    @Column(name="sex", nullable=false, length=1)
    public char getSex() {
        return this.sex;
    }
    
    public void setSex(char sex) {
        this.sex = sex;
    }




}


