package com.mycompany.assent.domain;
// Generated Dec 25, 2013 7:06:02 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name="warehouse"
    ,catalog="testHibernate"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Warehouse  implements java.io.Serializable {


     private Integer idWarehouse;
     private String name;
     private Set<BookWarehouse> bookWarehouses = new HashSet<BookWarehouse>(0);

    public Warehouse() {
    }

	
    public Warehouse(String name) {
        this.name = name;
    }
    public Warehouse(String name, Set<BookWarehouse> bookWarehouses) {
       this.name = name;
       this.bookWarehouses = bookWarehouses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_warehouse", unique=true, nullable=false)
    public Integer getIdWarehouse() {
        return this.idWarehouse;
    }
    
    public void setIdWarehouse(Integer idWarehouse) {
        this.idWarehouse = idWarehouse;
    }

    
    @Column(name="name", unique=true, nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="warehouse")
    public Set<BookWarehouse> getBookWarehouses() {
        return this.bookWarehouses;
    }
    
    public void setBookWarehouses(Set<BookWarehouse> bookWarehouses) {
        this.bookWarehouses = bookWarehouses;
    }




}


